config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#show'
  resources :users, only: [:show]
  resources :meals, except: [:edit, :update, :destroy]
  resources :ratings, only: [:index, :create, :destroy]
  resources :companies, only: [:index]
  get '/get_meals' => 'meals#grab_meals'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  has_many :ratings
  has_many :meals

  has_attached_file :profile_photo,
                    :styles => {  :medium => "300x300>",
                                  :thumb => "100x100>" },
                                  :default_url => "https://s3.amazonaws.com/beattadashi/users/profile_photos/000/000/005/medium/placeholder.jpg"
  validates_attachment_content_type :profile_photo, :content_type => /\Aimage\/.*\Z/

  def meals_since_sunday
    last_sunday_night = Date.today.beginning_of_week(:monday).to_datetime.change(hour: 1)
    meals = self.meals.order(created_at: :desc)
    meals.select { |m| m.created_at > last_sunday_night }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @meals = @user.meals_since_sunday
    @meal = @meals.shift
		@company_meals = @user.company.meals_since_sunday_sorted
  end

end

app/views/users/_star.html.erb
<div class="rating stars">
	<% num_times = rating.floor %>
	<% rating = rating.round(1) %>
	<% decimal = rating.to_s.last.to_i %>
	<% if num_times == 0 %>
		<%= fa_icon 'fa fa-star-o', class: 'yellow-stars' %>
	<% else %>
		<% num_times.times do %>
			<i class="fa fa-star yellow-stars"></i>
		<% end %>
		<% if decimal >= 5 %>
			<i class="fa fa-star-half-full yellow-stars"></i>
		<% end %>
	<% end %>
</div>

app/views/users/show.html.erb
  <div class="row">
  <div class="small-2 columns top-padding">
    <div class="small-avatar-wrap">
      <a href="<%= user_path(current_user) %>"><%= image_tag @user.profile_photo.url(:medium), :style => "max-width: 100%;" %></a>
    </div>
  </div>
  <div class="small-8 small-offset-1 columns top-padding welcome-name">
    <p>Welcome <%= current_user.name %></p>
  </div>
</div>

<div class="small-12 columns" align="center">
  <div class="show-template">
    <div class="small-12 small-centered columns">
  	<% if @meal %>
    	<h2>Today's Meal:</h2>
  		<%#= link_to image_tag(@meal.meal_photo.url(:medium), class: "todays-meal"), @meal %>
    <!-- jason's link fix, changed the max-width to 120% for better photo display -->
      <div class="meal-pic-wrapper">
		    <a href="<%= meal_path(@meal) %>"><%= image_tag @meal.meal_photo.url, class: 'meal-pic', :style => "max-width: 120%;" %></a>
      </div>
    <!-- end jason's link fix -->
  		<div>
  			<% if @meal.rating %>
  				<%= @meal.rating.round(2) %>
  				<%= render partial:'star', locals: {rating: @meal.rating} %>
  				<i class="fa fa-trophy"></i> <%= @company_meals.find_index(@meal) %>
  			<% else %>
  				"No Ratings Yet"
  			<% end %>
  		</div>
	<% else %>
		<div class="chef-hat">
			<%= link_to image_tag("chefhat.png"), new_meal_path %>
		</div>
		<h2><%= link_to "Hey chef, what did you make today?", new_meal_path, class: 'centered-text' %></h2>
  <% end %>
</div>

<div class="small-10 small-centered columns top-padding">
  <button class='radius' id="vote">Rate Lunches</button>
</div>

<div class="row">
  <div class="small-10 small-centered columns" >
    <h3 class="center-text bottom-padding">My Meals This Week</h3>
  </div>
</div>
<div class="row">
	<div class="small-10 small-centered columns" >
			<% i = 0 %>
			<% @meals.each do |meal| %>
      <div class="small-12 small-centered columns">
				<div class="user-mini-meal">
					<%= link_to (image_tag meal.meal_photo.url(:thumb)), meal %>
					<i class="fa fa-trophy"></i>
					<%= @company_meals.find_index(meal) %>
					<%= render partial: 'star', locals: {rating: meal.rating} %>
				</div>
      </div>
		<% i+=1 %>
		<% end %>
	</div>
</div>
</div>
</div>

<hr>

<div class="vote-template" hidden>
  <div class="row">
    <div class="small-6 small-centered columns center-text">
      <button class="tiny"><%= link_to 'Submit a Meal', new_meal_path, class: 'white-text' %></button>
    </div>
  </div>
  <div class="row">
    <div class="small-10 small-centered columns center-text">
      <h2>Vote on Meals!</h2>
    </div>
  </div>
  <div class="row">
    <div class="small-12 small-centered columns bottom-padding center-text" id="vote-meal-pic">
      <!-- meal image -->
    </div>
  </div>
  <div class="row">
    <div class="small-5 small-centered columns bottom-padding center-text" id="vote-meal-goalname">
      <!-- meal goal name -->
    </div>
  </div>
  <div class="row">
    <div class="small-5 small-centered columns bottom-padding center-text" id="vote-meal-comment">
      <!-- meal comment -->
    </div>
  </div>
  <div class="row">
    <div class="small-5 small-centered columns bottom-padding center-text" id="vote-meal-ingredients">
      <!-- meal ingredients -->
    </div>
  </div>
  <div class="row">
    <div class="small-5 small-centered columns bottom-padding center-text" id="vote-meal-nutrition">
      <!-- nutrition info goes here -->
    </div>
  </div>
  <div class="row">
    <div class="small-10 small-centered columns top-padding big-bottom-padding center-text">
        <span class="star-rating">
          <input type="radio" name="rating" id="rating-1"><i></i>
          <input type="radio" name="rating" id="rating-2"><i></i>
          <input type="radio" name="rating" id="rating-3"><i></i>
          <input type="radio" name="rating" id="rating-4"><i></i>
          <input type="radio" name="rating" id="rating-5"><i></i>
        </span>
    </div>
  </div>

</div>

<div class="finished-voting finished-voting-show-hide">
  <div class="row">
    <div class="small-4 columns">
      <button class="tiny"><%= link_to 'Profile', user_path(current_user), class: 'white-text' %></button>
    </div>
    <div class="small-4 small-offset-4 columns">
      <button class="tiny"><%= link_to 'Submit a Meal', new_meal_path, class: 'white-text' %></button>
    </div>
  </div>
  <div class="row">
    <div class="small-8 small-centered columns center-text" id="vote-meal-goalname">
      <h2>Good Job!</h2>
    </div>
  </div>
  <div class="row">
    <div class="small-10 small-centered columns center-text" id="vote-meal-comment">
      <p>Congrats! You have finished voting on all meals today. Come back later to vote more.</p>
    </div>
  </div>
  <div class="row">
    <div class="small-12 small-centered columns center-text" id="vote-meal-pic">
      <img style="max-width: 50%;" src="http://www.rawstory.com/rs/wp-content/uploads/2012/08/I-Voted-via-Shutterstock-615x345.jpg" />
    </div>
  </div>


<div class="small-12 small-centered columns top-padding center-text">
	<%= button_to "Go To Leaderboard!", ratings_path, method: 'get', class: 'button radius' %>
</div>