config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#show'
  resources :users, only: [:show]
  resources :meals, except: [:edit, :update, :destroy]
  resources :ratings, only: [:index, :create, :destroy]
  resources :companies, only: [:index]
  get '/get_meals' => 'meals#grab_meals'
end

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="icon" type="image/png" href="http://www.clker.com/cliparts/9/h/3/C/J/L/chef-hat-md.png">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Rate My Lunch</title>

    <%= stylesheet_link_tag    "application" %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Rate My Lunch</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="active"><a href="/">Homepage</a></li>
          <li class="active"><a href="/meals/new">Create A Meal</a></li>
          <li class="active"><a href="/ratings">Leaderboard</a></li>
          <% if current_user %>
            <% if current_user.admin %>
             <li class="active">
              <%= link_to "Company Data", companies_path %>
              </li>
            <% end %>
           <li class="active">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          <% end %>

        </ul>


      </section>
    </nav>

    <%= flash[:notice] %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>